//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentApp.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableCars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AvailableCars()
        {
            this.CarsOnRent = new HashSet<CarsOnRent>();
        }
    
        public int Id { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> Engine { get; set; }
        public Nullable<int> Year { get; set; }
        public string RegNumber { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> CarNameId { get; set; }
        public Nullable<int> AdminId { get; set; }
        public Nullable<int> EditedAddedBy { get; set; }
    
        public virtual Administrators Administrators { get; set; }
        public virtual CarNames CarNames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarsOnRent> CarsOnRent { get; set; }
    }
}
